theme: jekyll-theme-hacker
title: "Come funziona LiquidFeedback?"
description: "questo sito si propone di chiarire e spiegare in maniera esauriente il funzionamento e le meccaniche di liquid feedback."

