theme: jekyll-theme-hacker
title: "Come funziona LiquidFeedback?"
description: "Chiarire e spiegare in maniera esauriente il funzionamento e le meccaniche di LiquidFeedback è un'operazione per niente banale."

